### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getEditor' of undefined

### ISSUE THREAD

**Issue by RainbowDashDC** [abe33/minimap-color-highlight#2] opened 2014-12-30 15:47 UTC
[Enter steps to reproduce below:]

1. Open file
2. Toggle minimap

**Atom Version**: 0.165.0
**System**: Microsoft 
**Thrown From**: [minimap-color-highlight](https://github.com/abe33/minimap-color-highlight) package, v3.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getEditor' of undefined

```
At /c:/Users/Jared/.atom/packages/minimap-color-highlight/lib/minimap-color-highlight.coffee:72

TypeError: Cannot read property 'getEditor' of undefined
  at c:\Users\Jared\.atom\packages\minimap-color-highlight\lib\minimap-color-highlight.coffee:54:32
  at AtomColorHighlight.eachColorHighlightEditor (c:\Users\Jared\.atom\packages\atom-color-highlight\lib\atom-color-highlight.coffee:46:5)
  at MinimapColorHighlight.createViews (c:\Users\Jared\.atom\packages\minimap-color-highlight\lib\minimap-color-highlight.coffee:53:41)
  at c:\Users\Jared\.atom\packages\minimap-color-highlight\lib\minimap-color-highlight.coffee:1:1
  at Emitter.module.exports.Emitter.emit (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\node_modules\event-kit\lib\emitter.js:71:11)
  at Minimap.toggle (c:\Users\Jared\.atom\packages\minimap\lib\minimap.coffee:137:16)
  at atom-workspace.subscriptions.add.atom.commands.add.minimap:toggle (c:\Users\Jared\.atom\packages\minimap\lib\minimap.coffee:95:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:156:19)
  at Ipc.<anonymous> (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (c:\Users\Jared\AppData\Local\atom\app-0.165.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
  2x -0:00.0 minimap:toggle (atom-pane.pane.active)
```

### Config

```
{
  "core": {
    "themes": [
      "proton",
      "proton-bat"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v2.0.15
minimap, v3.4.9
minimap-color-highlight, v3.0.3
minimap-git-diff, v3.0.11
proton, v3.0.0
proton-bat, v2.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by zephraph** [comment] 2015-01-02 21:33
Same issue here. 

Occurred in 
```
C:\Users\..\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:126
```

**Comment by abe33** [comment] 2015-01-02 23:12
I'm in the process of upgrading atom-color-highlight and minimap to use custom elements so if someone feel to fix that and submit a PR it would be a great help :).

**Comment by abe33** [comment] 2015-01-03 17:05
I think this issue should be fixed with version 3.0.4 as I no longer rely on editor views. Can you confirm it?

**Comment by RainbowDashDC** [comment] 2015-01-03 20:22
Colors don't seem too appear at all in this version.

**Comment by abe33** [comment] 2015-02-03 10:36
I believe the issue is now fixed. Closing the ticket for the moment.

**Closed by abe33** 2015-02-03 10:36 UTC

**Comment by ismoiloff** [comment] 2018-11-13 02:01
The problem may be in included: <script src="{{ asset('js/app.js') }}" defer></script> Try to remove it. This can solve your problem
